### ISSUE TITLE
New file/rename/duplicate making form problem

### ISSUE THREAD

**Issue by santushnath** [ayu-theme/ayu-ace#2]
New file/rename/duplicate making form doesn't show fully, this form goes under the footer status bar. I think this is fixed very early. Thank You :)

**Comment by k15a** [comment]
Are you using ayu for the Ace online editor or for sublime text?

**Comment by santushnath** [comment]
No, it's AYU Theme
https://drive.google.com/open?id=0B1Atgq5uZC-YWWlHRFhpUG5PNkk
screenshot link

**Comment by k15a** [comment]
Yeah, that's ayu for sublime text. The repo is at https://github.com/dempfi/ayu and this is a known issue. Take a look at https://github.com/dempfi/ayu/issues/12
